In [1]:
my_list = [1,2,3]

In [2]:
import numpy as np 

In [3]:
np.array(my_list)

array([1, 2, 3])

In [4]:
arr = np.array(my_list)

In [5]:
arr

array([1, 2, 3])

In [6]:
my_mat = [[1,2,3],[4,5,6],[7,8,9]]

In [7]:
my_mat

[[1, 2, 3], [4, 5, 6], [7, 8, 9]]

In [8]:
np.array(my_mat)

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [9]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [10]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [11]:
np.zeros((5,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [12]:
np.ones(2)

array([1., 1.])

In [13]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.linspace(0,5,10)

array([0.        , 0.55555556, 1.11111111, 1.66666667, 2.22222222,
       2.77777778, 3.33333333, 3.88888889, 4.44444444, 5.        ])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.random.rand(5)

array([0.77146252, 0.40785742, 0.79369404, 0.29082321, 0.20792426])

In [17]:
np.random.rand(5,5)

array([[0.35879093, 0.19750223, 0.62758734, 0.41885712, 0.97640774],
       [0.35567176, 0.77137818, 0.18186229, 0.6984688 , 0.91307057],
       [0.33344205, 0.94429503, 0.89398246, 0.1254956 , 0.45242426],
       [0.50343897, 0.73852909, 0.09896767, 0.99034377, 0.05112889],
       [0.08682755, 0.83787854, 0.85910161, 0.44809843, 0.92977662]])

In [18]:
np.random.randn(4,4)

array([[ 0.66022818,  0.28633959, -0.83983021,  0.03312942],
       [-0.17362999,  0.49149706, -1.27226189,  0.28293238],
       [-1.06527943,  1.21440545, -0.90900202,  1.03488627],
       [ 1.55649633,  0.68950695,  1.58544403,  0.83233977]])

In [19]:
np.random.randint(1,100)

87

In [20]:
np.random.randint(1,100,10)

array([66, 95, 56, 87, 46, 60, 13, 55, 92, 83])

In [21]:
arr = np.arange(25)

In [22]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [23]:
ranrr = np.random.randint(0,100,10)

In [24]:
ranrr

array([73, 58, 91, 57, 64, 32, 45, 62, 36, 98])

In [25]:
arr.reshape(5,5)

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [26]:
ranrr

array([73, 58, 91, 57, 64, 32, 45, 62, 36, 98])

In [27]:
ranrr.max()

98

In [28]:
ranrr.min()

32

In [29]:
ran = ranrr.reshape(5,2)

In [30]:
ran

array([[73, 58],
       [91, 57],
       [64, 32],
       [45, 62],
       [36, 98]])

In [31]:
ranrr.argmax()

9

In [32]:
ranrr.argmin()

5

In [33]:
arr.shape

(25,)

In [34]:
arr = arr.reshape(5,5)

In [35]:
arr

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [36]:
arr.shape

(5, 5)

In [37]:
ran.shape

(5, 2)

In [38]:
from numpy.random import randint

In [39]:
randint(2,10)

4

#### Numpy Indexing and Selection

##### 1) Indexing

In [40]:
import numpy as np

In [41]:
arr = np.arange(0,11)

In [42]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [43]:
arr[8]

8

In [44]:
arr[1:5]

array([1, 2, 3, 4])

In [45]:
arr[0:5]

array([0, 1, 2, 3, 4])

In [46]:
arr[:6]

array([0, 1, 2, 3, 4, 5])

In [47]:
arr[5:]

array([ 5,  6,  7,  8,  9, 10])

In [48]:
import numpy as np

In [49]:
arr_2d = np.array([[5,25,10],[3,9,6],[10,100,60]])

In [50]:
arr_2d

array([[  5,  25,  10],
       [  3,   9,   6],
       [ 10, 100,  60]])

In [51]:
arr_2d[0]

array([ 5, 25, 10])

In [52]:
arr_2d[0][0]

5

In [53]:
arr_2d[0][1]

25

In [54]:
arr_2d[2,1]

100

In [55]:
arr_2d[2][1]

100

In [56]:
arr_2d

array([[  5,  25,  10],
       [  3,   9,   6],
       [ 10, 100,  60]])

In [57]:
arr_2d[0::2,1:]

array([[ 25,  10],
       [100,  60]])

In [58]:
arr_2d[0::2]

array([[  5,  25,  10],
       [ 10, 100,  60]])

##### 2)Selection

In [59]:
arr = np.arange(0,11)

In [60]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [61]:
bool_arr = arr > 5

In [62]:
bool_arr

array([False, False, False, False, False, False,  True,  True,  True,
        True,  True])

In [63]:
arr[bool_arr]

array([ 6,  7,  8,  9, 10])

In [64]:
arr[arr>5]

array([ 6,  7,  8,  9, 10])

In [65]:
arr[arr<3]

array([0, 1, 2])

#### Numpy Operations

In [66]:
import numpy as np

In [67]:
arr = np.arange(0,11)

In [68]:
arr

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [69]:
arr + arr

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [70]:
arr - arr

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [71]:
arr * arr 

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

In [72]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

##### Array with Scaler

In [73]:
arr + 100

array([100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110])

In [74]:
arr - 100

array([-100,  -99,  -98,  -97,  -96,  -95,  -94,  -93,  -92,  -91,  -90])

In [75]:
arr * 100

array([   0,  100,  200,  300,  400,  500,  600,  700,  800,  900, 1000])

In [76]:
arr / arr

C:\Users\hp\AppData\Local\Temp/ipykernel_14728/3001117470.py:1: RuntimeWarning: invalid value encountered in true_divide
  arr / arr


array([nan,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.,  1.])

In [77]:
arr ** 2

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100])

##### Universal Array function

In [78]:
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ,
       3.16227766])

In [79]:
np.exp(arr)

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03, 2.20264658e+04])

In [80]:
np.max(arr)

10

In [81]:
np.sin(arr)

array([ 0.        ,  0.84147098,  0.90929743,  0.14112001, -0.7568025 ,
       -0.95892427, -0.2794155 ,  0.6569866 ,  0.98935825,  0.41211849,
       -0.54402111])

In [82]:
np.log(arr)

C:\Users\hp\AppData\Local\Temp/ipykernel_14728/3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
       2.30258509])